config/routes.rb
Rails.application.routes.draw do
  
  
  get 'likes/create'
  get 'likes/destroy'
  root 'users#home'
  get '/about', to: 'users#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/succeed', to: 'users#succeed'
  get '/index',to: 'users#index'
  get '/users/:id', to: 'users#show'
  get '/search/tweetpost', to: 'users#search_all'
  get '/test', to: 'tweetposts#index'
  resources :users do
    member do
      get 'edit_password'
      get :following, :followers
    end
  end
  
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :tweetposts, only: [:create, :destroy, :show, :new] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  
  
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweetpost
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # 投稿にコメントを作成するメソッド
  def create
    @tweetpost = Tweetpost.find(params[:tweetpost_id])
    @comment = @tweetpost.comments.build(comment_params)
    @comment.user_id = current_user.id 
    
    if @comment.save
      render :index
    end
  end

  # 投稿についているコメントを削除するメソッド
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    end
  end


  private
    
    def comment_params
      params.require(:comment).permit(:content, :user_id, :tweetpost_id)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [tweetpost, comment] ) do |f|  %>
  <div>
    <%= f.text_area :content, placeholder: "コメントを書く", class:"comment-area" %>
  </div>
  <%= f.submit "コメントする", class:"btn comment-btn" %>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <%= link_to "#{comment.user.name}さん", user_path(comment.user.id), class:"comment-user-name" %>
    <div class="balloon5">
      <div class="faceicon">
        <% if comment.user.picture.blank? %>
          <%= link_to image_tag("212_0.jpeg", class:"comment-user-image") %>
        <% else %>
          <%= image_tag comment.user.picture.url, class: "comment-user-image" %>
        <% end %>
      </div>
      <div class="chatting">
        <div class="says">
          <p><%= simple_format(comment.content) %></p>
          <span class="comment-created"><%= comment[:created_at].strftime("%Y-%m-%d%H:%M") %></span>
        </div>
      </div>
    </div>
    <% if comment.user == current_user %>
      <%= link_to tweetpost_comment_path(comment.tweetpost_id, comment.id), class:"comment-delete-link", method: :delete, remote: true do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.tweetpost.comments }) %>")
$("textarea").val('')