config/routes.rb
Rails.application.routes.draw do
  
  
  get 'likes/create'
  get 'likes/destroy'
  root 'users#home'
  get '/about', to: 'users#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/succeed', to: 'users#succeed'
  get '/index',to: 'users#index'
  get '/users/:id', to: 'users#show'
  get '/search/tweetpost', to: 'users#search_all'
  get '/test', to: 'tweetposts#index'
  resources :users do
    member do
      get 'edit_password'
      get :following, :followers
    end
  end
  
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :tweetposts, only: [:create, :destroy, :show, :new] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  
  
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :tweetpost
  validates :user_id, presence: true
  validates :tweetpost_id, presence: true
  

  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_tweetpost

  def create
    @like = Like.create(user_id: current_user.id, tweetpost_id: params[:tweetpost_id])
    @likes = Like.where(tweetpost_id: params[:tweetpost_id])
    @tweetpost.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, tweetpost_id: params[:tweetpost_id])
    like.destroy
    @likes = Like.where(tweetpost_id: params[:tweetpost_id])
    @tweetpost.reload
  end

  private

  def set_tweetpost
    @tweetpost = Tweetpost.find(params[:tweetpost_id])
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if logged_in? %>
  <% unless tweetpost.like_user(current_user.id).blank? %>
    <%= link_to tweetpost_like_path(tweetpost_id: tweetpost.id ,id: tweetpost.likes[0].id), class:"link-clear", method: :delete, remote: true do %>
      <i class="fas fa-heart unlike"></i>
    <% end %>
  <% else %>
    <%= link_to tweetpost_likes_path(tweetpost.id), class:"link-clear", method: :post, remote: true do %>
      <i class="far fa-heart like"></i>
    <% end %>
  <% end %>

<% else %>
  <%= link_to login_path, class:"link-clear", method: :get do %>
    <i class="far fa-heart like"></i>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @tweetpost.id %>').html("<%= j(render partial: 'likes/like', locals: {tweetpost: @tweetpost}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @tweetpost.id %>').html("<%= j(render partial: 'likes/like', locals: {tweetpost: @tweetpost}) %>");