config/routes.rb
Rails.application.routes.draw do
  
  
  get 'likes/create'
  get 'likes/destroy'
  root 'users#home'
  get '/about', to: 'users#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/succeed', to: 'users#succeed'
  get '/index',to: 'users#index'
  get '/users/:id', to: 'users#show'
  get '/search/tweetpost', to: 'users#search_all'
  get '/test', to: 'tweetposts#index'
  resources :users do
    member do
      get 'edit_password'
      get :following, :followers
    end
  end
  
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :tweetposts, only: [:create, :destroy, :show, :new] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  
  
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  
  
  has_many :tweetposts, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  # active_relationshipsの関係性を作るためにrelationshipモデルを使用すると明示している.foreign_keyによりfollower_idとidが繋がる.
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  # followingシンボルを用いたいのでfollowedを示しそこからfollowed_idを取得する.
  has_many :following, through: :active_relationships, source: :followed

  # followed_idとuserモデルのidとの関連性を明示
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  before_save { self.email = email.downcase }
  mount_uploader :picture, PictureUploader
  validates :name, presence: true, length:{ maximum: 20 }
  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length:{ maximum: 50 },
                    format: { with: VALID_EMAIL },
                    # 大文字小文字の型を無視する
                    uniqueness: { case_sensitive: false }
  validates :profile, length:{ maximum: 400 }
  has_secure_password
  validates :password, presence: true, length:{ minimum: 6}, allow_nil:true
  validate :picture_size
  mount_uploader :picture, PictureUploader


  # フォローしているユーザーの投稿を取得
  def feed
    following_ids = "SELECT followed_id FROM relationships
                    WHERE follower_id = :user_id"
    Tweetpost.where("user_id IN (#{following_ids})
                    OR user_id = :user_id", user_id: id)
  end
   
  # 引数に与えられたユーザーidをfollowed_idに追加する
  def follow(other_user)
    following << other_user
  end


  # 引数に与えられたユーザーidをfollowed_idから探し出し存在すれば削除
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # other_userがfollowed_idに存在するか確認するメソッと
  def following?(other_user)
    following.include?(other_user)
  end

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  
  
  def home 
    @tweetposts = current_user.tweetposts.build if logged_in?
    if logged_in?
      if params[:q] && params[:q].reject { |key, value| value.blank? }.present?
        @q = current_user.feed.ransack(current_user_tweetposts_search_params)
        @feed = @q.result.paginate(page: params[:page], per_page:10)
      else
        @q = Tweetpost.none.ransack
        @feed = current_user.feed.paginate(page: params[:page], per_page:10)
      end
      @url = root_path
    end
  end

  def search_all
    if params[:q] && params[:q].reject { |key, value| value.blank? }.present?
      @q = Tweetpost.ransack(all_tweetpost_search_params, activated_true: true)
    else
      @q = Tweetpost.ransack(activated_true: true)
    end
    @tweetposts = @q.result.paginate(page: params[:page],per_page:15)
    @url = search_tweetpost_path
  end

  def about
  end

  def show
    @user = User.find(params[:id])
    @tweetposts = @user.tweetposts.paginate(page: params[:page], per_page:15)
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit 
    @user = User.find(params[:id])
  end

  def edit_password
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # データーベースから取得したオブジェクトを更新/保存
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def succeed
  end

  def index
    if params[:q] && params[:q].reject { |key, value| value.blank? }.present?
      @q = User.ransack(search_params, activated_true: true)
    else
      @q = User.ransack(activated_true: true)
    end
    @users = @q.result
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :profile, :picture, :password, :password_confirmation)
    end

    def user_search_params
      params.require(:q).permit(:name_cont)
    end

    def all_tweetpost_search_params
      params.require(:q).permit(:content_cont)
    end

    def current_user_tweetposts_search_params
      params.require(:q).permit(:content_cont)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def user_name(user)
    p user.name
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary btn-follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form"> 
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_home_not_login.html.erb
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>One Page Wonder - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/one-page-wonder.min.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">STUNI</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "新規会員登録", signup_path, class:"nav-link"  %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", login_path, class:"nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead text-center text-white">
      <div class="masthead-content">
        <div class="container">
          <h1 class="masthead-heading mb-0">Welcome STUNI！</h1>
          <h4 class="masthead-subheading mb-0">ぬい撮り写真をシェアする専用SNS</h4>
          <a href="#" class="rounded-pill mt-5"><%= link_to "みんなのぬい撮りをみる", search_tweetpost_path, class:"btn btn-primary btn-xl " %></a>
        </div>
      </div>
      
    </header>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 order-lg-2">
            <div class="p-5">
              <%= link_to image_tag("teddy-bear-792279_1920.jpg", alt:"logoマーク", class:"img-fluid rounded-circle") %>
            </div>
          </div>
          <div class="col-lg-6 order-lg-1">
            <div class="p-5">
              <h2 class="display-4">What is STUNI?</h2>
              <p>STUNIはぬいどりの写真をシェアするための専用SNSです。<br>STUNIを使うことで世界中のぬいぐるみが出かけた記録や思い出を探すことができます。</p>
              
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6">
            <div class="p-5">
              
              <%= link_to image_tag("dreams-1593708_1920.jpg", alt:"logoマーク", class:"img-fluid rounded-circle") %>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="p-5">
              <h2 class="display-4">How to STUNI?</h2>
              <p>30秒の会員登録でSTUNIを始めることができます。<br>あなたもぬいぐるみたちの世界へ飛び込んでみましょう！</p>
              
            </div>
          </div>
        </div>
      </div>
    </section>

    

    <!-- Footer -->
    <footer class="py-5 bg-black">
      <div class="container">
        <p class="m-0 text-center text-white small"></p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

app/views/users/_search_name_form.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :name_cont, 'User Search' %>
  <%= f.text_field :name_cont, placeholder:"ユーザー名を検索する",class: "form-control" %>

  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-unfollow" %>
<% end %>

app/views/users/about.html.erb
<main>
 <div class="container aboutpage">
 <div class="row">
  <div class="col-9 col-md-9"><img src="https://placehold.jp/700x500.png" class="about_topimage"></div>
  <div class="col-3 col-md-3">
   <a>お迎えする</a>
   <a>フォーム位置</a>
   <a>フォームに</a>
   <a>フォーム３</a>
  </div>
 </div>
 
 <div class="row">
  <div class="col-12 col-md-12">about teddy</div>
 </div>

<% if logged_in? %>
  <a>Q:どのようなサービスですか？</a><br>
  <a>A:あなたのにんぎょうが主役のサービスです</a><br>
  <a>Q:どのようなジャンルがありますか？</a><br>
  <a>A:ジャンルは無限です。あなたが作りたい世界を作りましょう。</a><br>
  <%= link_to "ログアウト", logout_path, method: :delete %>
<% else %>
  <a>どのようなサービスですか？</a><br>
  <a>どのようなサービスですか？</a><br>
  <%= link_to "ログイン", login_path %>
<% end %>

<%= link_to  "さあにんぎょうの世界に入ってみましょう!", root_path,class: "btn btn-primary" %>
</div>
</main>

app/views/users/edit.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class="profile-edit-box">
    <div class="row">
      <div class="col-md-3 edit-sidebar">
        <nav class="nav flex-column">
          <a class="nav-link "><%= link_to "プロフィール編集", edit_user_path(current_user), class:"edit-sidebar-link" %></a>
          <a class="nav-link "><%= link_to "パスワード変更", edit_password_user_path(current_user), class:"edit-sidebar-link" %></a>
        </nav>
      </div>
      <div class="col-md-8 edit-main">
        <%= form_for(@user) do |f| %>

          <div class="edit-profile-image-box">
            <span class="label-profile-image"><%= f.label :プロフィール画像 %></span>
            <div class="edit-image-box">
              <% if @user.picture.blank? %>
                <%= link_to image_tag("212_0.jpeg", alt:"logoマーク", class:"edit-user-image1") %>
              <% else %>
                <%= image_tag @user.picture.url, class:"edit-user-image2" %>
              <% end %>
              
            </div>
            <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class:"edit-file-upload" %>
          </div>

          <div class="edit-profile-name">
            <div class="edit-name-else-error">
              <span class="label-profile-name"><%= f.label :ユーザー名 %></span>
              <%= f.text_field :name, class:"form-control edit-form-name" %>
            </div>
            <%= render "shared/name_error_messages" %>
          </div>

          <div class="edit-profile-email">
            <div class="edit-email-else-error">
              <span class="label-profile-email"><%= f.label :メールアドレス %></span>
              <%= f.email_field :email, class:"form-control edit-form-email" %>
            </div>
            <%= render "shared/email_error_messages" %>
          </div>

          <div class="edit-profile-intro">
            <div class="edit-intro-else-error">
              <span class="label-profile-intro"><%= f.label :自己紹介 %></span>
              <%= f.text_area :profile,　placeholder: "自己紹介を入力しましょう！（400文字以内）", class:"form-control edit-form-intro", rows: 10, cols: 40 %>
            </div>
          </div>
          <%= f.submit "この内容で保存", class:"btn btn-primary edit-btn" %>
        <% end %>

        <script type="text/javascript">
          $('#micropost_picture').bind('change', function() {
            var size_in_megabytes = this.files[0].size/1024/1024;
            if (size_in_megabytes > 5) {
              alert('Maximum file size is 5MB. Please choose a smaller file.');
            }
          });
        </script>
  </div>
 </div>
 </div>
</div>

app/views/users/edit_password.html.erb
<%= render 'shared/header' %>
<div class="container">
  <div class="profile-edit-box">
    <div class="row">
      <div class="col-md-3 edit-sidebar">
        <nav class="nav flex-column">
          <a class="nav-link "><%= link_to "プロフィール編集", edit_user_path(current_user), class:"edit-sidebar-link" %></a>
          <a class="nav-link "><%= link_to "パスワード変更", edit_password_user_path(current_user), class:"edit-sidebar-link" %></a>
        </nav>
      </div>
      <div class="col-md-8 edit-password">
        <%= form_for(@user) do |f| %>
        <div class="edit-password-new-box">
          <div class="edit-new-else-error">
            <span class="label-password-new"><%= f.label :新しいパスワード%></span>
            <%= f.password_field :password, class:"form-control password-form-new" %>
          </div>
          <%= render "shared/password_error_messages" %>
        </div>

        <div class="edit-password-conf-box">
          <div class="edit-conf-else-error">
            <span class="label-password-conf"><%= f.label :password_confirmation_change %></span>
            <%= f.password_field :password_confirmation, class:"form-control password-form-conf" %>
          </div>
          <%= render "shared/password_confirmation_error_messages" %>
        </div>

          <%= f.submit "変更する", class:"btn btn-primary btn-password" %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/home.html.erb
<% if logged_in? %>
  <%= render 'shared/header' %>
  <main>
    <div class="home-background">
      <div class="col-md-8 home-post-box">
        <section>
          <%= render 'shared/feed' %>
        </section>
      </div>
      <div class="col-md-4 home-sidebar-box">
        <% if current_user.picture.blank? %>
          <%= link_to image_tag("212_0.jpeg", class:"sidebar-user-image") %>
        <% else %>
          <%= image_tag current_user.picture.url, class:"sidebar-user-image" %>
        <% end %>
        <%= link_to current_user.name, user_path(current_user), class:"sidebar-user-name" %>
        <%= render 'shared/tweet_form'%>
      </div>
    </div>
  </main>
<% else %>
  
  <%= render 'home_not_login' %>
<% end %>

app/views/users/index.html.erb
<div class="row">
 <%= render 'users/search_name_form' %>
</div>

<% unless @users.empty? %>
 <% @users.each do |user| %>
  <%= user.name %>
  <%= user.email %>
 <% end %>
<% else %>
 <p>ユーザーが見つかりませんでした</p>
<% end %>

app/views/users/new.html.erb
<div class="signup-container">
  <div class="logo-contaner">
    <%= link_to image_tag("P_Tx7ZkSygyAMwL1542268159_1542268190", alt:"logoマーク", class:"signup-logo"), root_path %>
  </div>
  <div class="signup-form-container">
    <p class="signup-p1">STUNIに登録する</p>
    <%= form_for(@user) do |f| %>
      <span class="signup-label"><%= f.label :ニックネーム（登録後に変更可能） %></span>
      <%= f.text_field :name, class:'form-control signup-form', placeholder: "例:テディー" %>
      <%= render "shared/name_error_messages" %>

      <span class="signup-label"><%= f.label :email %></span>
      <%= f.email_field :email, class:'form-control signup-form', placeholder: "例:メールアドレス" %>
      <%= render "shared/email_error_messages" %>

      <span class="signup-label"><%= f.label :パスワード %></span>
      <%= f.password_field :password, class:'form-control signup-form', placeholder: "半角英数で6文字以上" %>
      <%= render "shared/password_error_messages" %>

      <span class="signup-label"><%= f.label :パスワードの確認 %></span>
      <%= f.password_field :password_confirmation, class:'form-control signup-form', placeholder: "確認のために再度入力" %>
      <%= render "shared/password_confirmation_error_messages" %>

      <%= f.submit "STUNIを始める", class:"btn btn-signup" %>
    <% end %>
    <p class="signup-p2">アカウントを持っている方は<%= link_to "こちら", login_path %>からログイン</p>
  </div>
</div>

app/views/users/search_all.html.erb
<%= render 'shared/header'%>
<div class="search-container">
  <div class="search-form-box">
    <%= search_form_for @q, url: @url do |f| %>
    <%= f.text_field :content_cont, placeholder: "キーワードで検索する", class:"form-control form-search" %>
    <%= f.submit "検索", class:"btn btn-search" %>
    <%= link_to "全てのぬいどりを見る", search_tweetpost_path, class:"all-nuidori" %>
    <% end %>
  </div>
  <div class="search-result">
    <%= render @tweetposts, showpage: true %>
  </div>
  <div class="search-pagination">
    <%= will_paginate @tweetposts,  :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
  </div>
</div>

app/views/users/show.html.erb
<head>
  <title>STUNI</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="users.scss" />
</head>
<main>
  <%= render 'shared/header' %>
    <div class="show-container">
      <div class="show-user-image-box">
        <% if @user.picture.blank? %>
          <%= link_to image_tag("212_0.jpeg", alt:"logoマーク", class:"show-user-image1") %>
        <% else %>
          <%= image_tag @user.picture.url, class:"show-user-image2" %>
        <% end %>
      </div>
      <div class="show-userprofile-box">
        <div class="name-follow-edit-box">
          <span class="show-user-name"><%= user_name(@user) %></span>
          <%# ログインユーザーidとプロフ画面のユーザーidが一致すれば編集ボタンを表示。　一致しない場合かつログイン中の場合フォローボタン表示%>
          <% if logged_in? %>
            <% if current_user.id == @user.id %>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle dropdown-self" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-cog"></i>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <%= link_to "編集", edit_user_path(current_user), class:"show-edit dropdown-item" %>
                  <%= link_to "ログアウト", logout_path, method: :delete, class:"show-edit dropdown-item" %>
                </div>
              </div>
            <% else %>
              <%= render 'follow_form' if logged_in? %>
            <% end %>
          <% else %>          
            <%= link_to "フォローする", login_path, class: "btn btn-primary btn-follow" %>
          <% end %>
          
        </div>
        <div class="count-box">
          <ul>
            <li>投稿<span class="post-strong"><%= @user.tweetposts.count %></span>件</li>
            <li><%= render 'shared/follow_count' %></li>
          </ul>
        </div>
        <%# ユーザープロフィール表示の条件分岐 %>
        <div class="show-profile-box">
          <% if @user.profile.blank? %>
            <% if current_user?(@user) %> 
              <p><%= link_to "自分のプロフィールを更新してみましょう", edit_user_path(current_user) %></p>
            <% else %>
              <p><%= "#{@user.name}さんのプロフィールにはまだ何も書かれていません" %></p>
            <% end %>
          <% else %>
            <p ><%= simple_format(@user.profile) %> </p>
          <% end %>
        </div>
      </div>
    </div>
 

  <% if @user.tweetposts.any? %>
  <div class="show-float-clear">
    <ol>
      <%= render @tweetposts, showpage: true %>
    </ol>
  </div>
    <div class="show-pagination">
      <%= will_paginate @tweetposts,  :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
    </div>
  <% end %>
  
</main>

app/views/users/succeed.html.erb
<%= render 'shared/header' %>
<h1>ユーザー登録が完了しました。さあ新しい背化に入ってみましょう! </h1>