config/routes.rb
Rails.application.routes.draw do
  
  
  get 'likes/create'
  get 'likes/destroy'
  root 'users#home'
  get '/about', to: 'users#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/succeed', to: 'users#succeed'
  get '/index',to: 'users#index'
  get '/users/:id', to: 'users#show'
  get '/search/tweetpost', to: 'users#search_all'
  get '/test', to: 'tweetposts#index'
  resources :users do
    member do
      get 'edit_password'
      get :following, :followers
    end
  end
  
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :tweetposts, only: [:create, :destroy, :show, :new] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  
  
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_email_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_message">
    <ul>
      <% @user.errors.full_messages_for(:email).each do |er| %>
        <li><%= er %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed.any? %>
  <div class="feed-float-clear">
    <ol>
      <% #@feedの各要素がTweetpostクラスを持っているため、_tweetpostパーシャルを呼び出すことができる %>
      <%= render @feed %>
    </ol>
    </div>
    <div class="home-pagination">
      <%= will_paginate @feed,  :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
    </div>
  <% else %>
    <%= link_to "ぬいどりを探して、気になる子をフォローしてみましょう！", search_tweetpost_path %>
<% end %>

app/views/shared/_follow_count.html.erb
<% @user ||= current_user %>
 <div>
  <a class="following-count">フォロー数<span class="post-strong"><%= @user.following.count %></span></a>
  
  <a class="followers-count">フォロワー数<span class="post-strong"><%= @user.followers.count %></span></a>

 </div>

app/views/shared/_footer.html.erb
<% if logged_in? %>
  <footer>
    <div class="footer-container">
        <ul>
          <li>
            <%= link_to root_path, method: :get do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li>
            <%= link_to search_tweetpost_path, method: :get do %>
              <i class="fas fa-search"></i>
            <% end %>
          </li>
          <li>
            <%= link_to new_tweetpost_path, method: :get do %>
              <i class="fas fa-plus"></i>
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user), method: :get do %>
              <i class="fas fa-paw"></i>
            <% end %>
          </li>
          
        </ul>
    </div>
  </footer>
<% else %>
  <footer>
    <div class="container">
    <div class="row">
      <div class="col-4 col-md-4 teddylogo"><%= link_to  "logo", root_path %></div>
      <div class="col-8 col-md-8">
        <ul>
          <li><%= link_to "ログインする", login_path %></li>
          <li>全ユーザーの投稿をみる</li>
        </ul>
      </div>
    </div>
    </div>
  </footer>
<% end %>

app/views/shared/_header.html.erb
<% if logged_in? %>
  <header>
    <div class="loggedin-header-container">
        <ul>
          <li>
            <%= link_to image_tag("P_Tx7ZkSygyAMwL1542268159_1542268190", alt:"logoマーク", class:"logo-stuni"), root_path %>
          </li>
          <li>
            <%= link_to search_tweetpost_path, class:"link-clear header-icon1", method: :get do %>
              <i class="fas fa-search"></i>
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user), class:"link-clear header-icon2", method: :get do %>
              <i class="fas fa-paw"></i>
            <% end %>
          </li>
          
        </ul>
    </div>
  </header>
<% else %>
  <header>
    <div class="notloggedin-header-container">
        <ul>
          <li><%= link_to image_tag("P_Tx7ZkSygyAMwL1542268159_1542268190", alt:"logoマーク", class:"logo-stuni"), root_path %></li>
          <li><%= link_to "ログインする", login_path, class:"header-path" %></li>
          <li><%= link_to "新規会員登録", signup_path, class:"header-path" %></li>
        </ul>
      </div>
    </div>
  </header>
<% end %>

app/views/shared/_name_error_messages.html.erb
<% if @user.errors.any? %>
 <div class="error_message">
  <ul>
    <% @user.errors.full_messages_for(:name).each do |er| %>
     <li><%= er %></li>
    <% end %>
  </ul>
 </div>
<% end %>

app/views/shared/_password_confirmatio_error_messages.html.erb
<% if @user.errors.any? %>
 <div class="error_message">
  <ul>
    <% @user.errors.full_messages_for(:password_confirmation).each do |er| %>
     <li><%= er %></li>
    <% end %>
  </ul>
 </div>
<% end %>

app/views/shared/_password_confirmation_error_messages.html.erb
<% if @user.errors.any? %>
 <div class="error_message">
  <ul>
    <% @user.errors.full_messages_for(:password_confirmation).each do |er| %>
     <li><%= er %></li>
    <% end %>
  </ul>
 </div>
<% end %>

app/views/shared/_password_error_messages.html.erb
<% if @user.errors.any? %>
 <div class="error_message">
  <ul>
    <% @user.errors.full_messages_for(:password).each do |er| %>
     <li><%= er %></li>
    <% end %>
  </ul>
 </div>
<% end %>

app/views/shared/_search_tweetpost_form.html.erb
<%= search_form_for @q, url: @url do |f| %>
  <%= f.label :content_cont, 'Tweetpost Search' %>
  <%= f.text_field :content_cont, placeholder: "投稿を検索する", class:"form-control" %>

  <%= f.submit "検索", class:"btn btn-primary" %>
<% end %>

app/views/shared/_tweet_form.html.erb
<%= form_for(@tweetposts) do |f| %>
    <%= f.text_area :content, placeholder: "お出かけした思い出をつぶやきましょう（画像必須）", class:"tweet-area"%>
    <label for="file_photo" class="label">
    <i class="fas fa-camera-retro"></i>
      <%= f.file_field :picture, id:"file_photo", style:"display: none", accept: "image/jpeg,image/gif,image/png"%>
    </label>
    <%= f.submit "投稿", class: "btn post-btn" %>
  <% end %>

  <script type="text/javascript">
  $('#tweetpost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('５MB以下のファイルを選択してください');
    }
  });

  
</script>